### ISSUE TITLE
Class "external_api" not found

### ISSUE THREAD

**Issue by grawity** [moodlehq/moodle-webservice_xmlrpc#5]
With 2022110800 on Moodle 4.2, I am getting:

```
xmlrpc.client.Fault: <Fault 404: 'Class "external_api" not found'>
```

Temporarily patched it locally, but I have no idea if this is the correct fix.

```diff
diff --git a/locallib.php b/locallib.php
index 8ba5031..53f6c9f 100644
--- a/locallib.php
+++ b/locallib.php
@@ -29,6 +29,8 @@ defined('MOODLE_INTERNAL') || die();
 
 require_once("$CFG->dirroot/webservice/lib.php");
 
+use core_external\external_api;
+
 /**
  * XML-RPC service server implementation.
  *
```

**Comment by stronk7** [comment]
Hi @grawity,

sorry for the late response, somehow I missed it. The fix for this plugin to work with the external changes that happened in Moodle 4.2 was done by #3.

But it seems that we never made a release with them. I've now released `1.0.3` and soon will be also available in the [Plugins database](https://moodle.org/plugins/webservice_xmlrpc/versions).

Ciao :-)
